/* Puzzle levels. Generated by tools/emit.js — do not edit by hand.

   Every par is a proven minimum: tools/solve.js searches all placements of k
   cells near the dirt, smallest k first, and simulates each to see whether the
   board empties. "solutions" is how many placements at par work, which is the
   honest measure of how tight a level is. The stored solution is one of them,
   used by the Reveal button.

   Map legend: '.' empty, 'o' dirt, '#' rock. */
window.LIFE_LEVELS = [
  {
    "key": "first-speck",
    "title": "First speck",
    "blurb": "One block of grime. A single cell is enough — find where.",
    "map": "................\n................\n................\n................\n................\n.......oo.......\n.......oo.......\n................\n................\n................\n................\n................",
    "par": 1,
    "solutions": 16,
    "gens": 5,
    "solution": [
      [
        6,
        3
      ]
    ]
  },
  {
    "key": "loose-change",
    "title": "Loose change",
    "blurb": "Three lumps, and still only one cell needed.",
    "map": "................\n................\n................\n...ooo....o.....\n..........o.....\n..........o.....\n.....oo.........\n....o..o........\n.....oo.........\n................\n................\n................",
    "par": 1,
    "solutions": 25,
    "gens": 22,
    "solution": [
      [
        5,
        1
      ]
    ]
  },
  {
    "key": "bedrock",
    "title": "Bedrock",
    "blurb": "Rock is inert: nothing lives there and you cannot build on it.",
    "map": "................\n................\n...ooo..........\n............o...\n.........o..o...\n....ooo..o..o...\n.........o......\n................\n................\n..##########....\n................\n................",
    "par": 1,
    "solutions": 22,
    "gens": 42,
    "solution": [
      [
        3,
        0
      ]
    ]
  },
  {
    "key": "odd-pair",
    "title": "Odd pair",
    "blurb": "This one wants two.",
    "map": "................\n................\n................\n...o............\n..o.o.......o...\n...o........o...\n............o...\n................\n................\n................\n................\n................",
    "par": 2,
    "solutions": 7,
    "gens": 34,
    "solution": [
      [
        4,
        1
      ],
      [
        2,
        2
      ]
    ]
  },
  {
    "key": "quarry",
    "title": "Quarry",
    "blurb": "Plenty of dirt, plenty of rock, two cells.",
    "map": "................\n..o.............\n.o.o..#.....oo..\n..o...#oo...oo..\n......o..o......\n......#oo.......\n......#.....o...\n......#.....o...\n............o...\n................\n................\n................",
    "par": 2,
    "solutions": 10,
    "gens": 14,
    "solution": [
      [
        10,
        1
      ],
      [
        2,
        2
      ]
    ]
  },
  {
    "key": "long-wall",
    "title": "Long wall",
    "blurb": "Five lumps split by a wall.",
    "map": "................\n.............o..\n..o.....o....o..\n.o.o....o#...o..\n..o.....o#......\n.........#......\n.........#..o...\n....oo...#..o...\n....o.o..#..o...\n.....o...#......\n.........#......\n................",
    "par": 2,
    "solutions": 13,
    "gens": 47,
    "solution": [
      [
        11,
        2
      ],
      [
        2,
        6
      ]
    ]
  },
  {
    "key": "bullseye",
    "title": "Bullseye",
    "blurb": "Two lumps, one cell, one place it can go.",
    "map": "................\n................\n................\n................\n................\n..o.............\n.o.o....ooo.....\n..o.............\n................\n................\n................\n................",
    "par": 1,
    "solutions": 1,
    "gens": 49,
    "solution": [
      [
        2,
        6
      ]
    ]
  },
  {
    "key": "hairline",
    "title": "Hairline",
    "blurb": "Eight cells of dirt and exactly one answer.",
    "map": "................\n....oo..........\n....o.o.........\n.....o..........\n................\n................\n.ooo............\n................\n................\n................\n................\n................",
    "par": 1,
    "solutions": 1,
    "gens": 26,
    "solution": [
      [
        3,
        4
      ]
    ]
  },
  {
    "key": "split",
    "title": "Split",
    "blurb": "The wall separates them. One cell still does both.",
    "map": "................\n.........#......\n.........#......\n.........#......\n.....oo..#......\n.....o.o........\n......o.........\n................\n................\n........ooo.....\n................\n................",
    "par": 1,
    "solutions": 1,
    "gens": 15,
    "solution": [
      [
        8,
        7
      ]
    ]
  },
  {
    "key": "housekeeping",
    "title": "Housekeeping",
    "blurb": "Five lumps, eighteen cells of dirt, one cell of yours.",
    "map": "................\n.oo.............\n.oo........o....\n..........o.o...\n...........o....\n.....o..........\n.....o..........\n.oo..o..........\n.oo.......ooo...\n................\n................\n................",
    "par": 1,
    "solutions": 1,
    "gens": 71,
    "solution": [
      [
        7,
        7
      ]
    ]
  },
  {
    "key": "slow-burn",
    "title": "Slow burn",
    "blurb": "One cell, and well over a hundred generations of fallout.",
    "map": "................\n...ooo...oo.....\n.........oo#....\n...........#....\n...........#....\n...........#....\n................\n..........o.....\n.....oo...o.....\n.....oo...o.....\n................\n................",
    "par": 1,
    "solutions": 1,
    "gens": 137,
    "solution": [
      [
        9,
        8
      ]
    ]
  },
  {
    "key": "through-wall",
    "title": "Through the wall",
    "blurb": "Two cells. Only one pair in the whole board works.",
    "map": "................\n................\n.......o........\n.......o........\n.......o........\n.##########.....\n................\n.....o..........\n....o.o.........\n.....o..........\n................\n................",
    "par": 2,
    "solutions": 1,
    "gens": 64,
    "solution": [
      [
        6,
        6
      ],
      [
        6,
        7
      ]
    ]
  },
  {
    "key": "two-of-a-kind",
    "title": "Two of a kind",
    "blurb": "Symmetrical, and no kinder for it.",
    "map": "................\n........#.......\n.....o..#.o.....\n....o.o.#.o.....\n.....o..#.o.....\n........#.......\n........#.......\n........#.......\n................\n................\n................\n................",
    "par": 2,
    "solutions": 1,
    "gens": 84,
    "solution": [
      [
        5,
        3
      ],
      [
        9,
        3
      ]
    ]
  }
];
