/* Puzzle levels for all four goals. Generated by tools/emit-challenges.js —
   do not edit by hand.

   clear / hold / bloom targets are exhaustive results: tools/search.js tries
   every placement of k cells near the dirt, so "fewest possible" and "best
   possible" mean exactly that. Sweep targets are the best a search over
   pattern stamps could find, which is an honest best known rather than a
   proof — beating one is a real result.

   Map legend: '.' empty, 'o' dirt, '#' rock, '*' a cell that must be visited. */
window.LIFE_GOALS = {
  "clear": {
    "key": "clear",
    "name": "Clear",
    "verb": "fewest cells",
    "proven": true,
    "tagline": "Empty the board using as few cells of your own as you can."
  },
  "hold": {
    "key": "hold",
    "name": "Hold on",
    "verb": "fewest cells",
    "proven": true,
    "tagline": "Empty the board — but if only dirt is left alive, you have lost."
  },
  "bloom": {
    "key": "bloom",
    "name": "Bloom",
    "verb": "most alive",
    "proven": true,
    "tagline": "Add up to two cells and grow the board as large as you can by generation 40."
  },
  "sweep": {
    "key": "sweep",
    "name": "Sweep",
    "verb": "fewest generations",
    "proven": false,
    "tagline": "Every marked cell must be alive at least once. Take as few generations as you can."
  }
};
window.LIFE_LEVELS = {
  "clear": [
    {
      "key": "first-speck",
      "title": "First speck",
      "blurb": "One block of grime. A single cell is enough — find where.",
      "map": "................\n................\n................\n................\n................\n.......oo.......\n.......oo.......\n................\n................\n................\n................\n................",
      "par": 1,
      "solutions": 16,
      "gens": 5,
      "solution": [
        [
          6,
          3
        ]
      ]
    },
    {
      "key": "loose-change",
      "title": "Loose change",
      "blurb": "Three lumps, and still only one cell needed.",
      "map": "................\n................\n................\n...ooo....o.....\n..........o.....\n..........o.....\n.....oo.........\n....o..o........\n.....oo.........\n................\n................\n................",
      "par": 1,
      "solutions": 25,
      "gens": 22,
      "solution": [
        [
          5,
          1
        ]
      ]
    },
    {
      "key": "bedrock",
      "title": "Bedrock",
      "blurb": "Rock is inert: nothing lives there and you cannot build on it.",
      "map": "................\n................\n...ooo..........\n............o...\n.........o..o...\n....ooo..o..o...\n.........o......\n................\n................\n..##########....\n................\n................",
      "par": 1,
      "solutions": 22,
      "gens": 42,
      "solution": [
        [
          3,
          0
        ]
      ]
    },
    {
      "key": "odd-pair",
      "title": "Odd pair",
      "blurb": "This one wants two.",
      "map": "................\n................\n................\n...o............\n..o.o.......o...\n...o........o...\n............o...\n................\n................\n................\n................\n................",
      "par": 2,
      "solutions": 7,
      "gens": 34,
      "solution": [
        [
          4,
          1
        ],
        [
          2,
          2
        ]
      ]
    },
    {
      "key": "quarry",
      "title": "Quarry",
      "blurb": "Plenty of dirt, plenty of rock, two cells.",
      "map": "................\n..o.............\n.o.o..#.....oo..\n..o...#oo...oo..\n......o..o......\n......#oo.......\n......#.....o...\n......#.....o...\n............o...\n................\n................\n................",
      "par": 2,
      "solutions": 10,
      "gens": 14,
      "solution": [
        [
          10,
          1
        ],
        [
          2,
          2
        ]
      ]
    },
    {
      "key": "long-wall",
      "title": "Long wall",
      "blurb": "Five lumps split by a wall.",
      "map": "................\n.............o..\n..o.....o....o..\n.o.o....o#...o..\n..o.....o#......\n.........#......\n.........#..o...\n....oo...#..o...\n....o.o..#..o...\n.....o...#......\n.........#......\n................",
      "par": 2,
      "solutions": 13,
      "gens": 47,
      "solution": [
        [
          11,
          2
        ],
        [
          2,
          6
        ]
      ]
    },
    {
      "key": "bullseye",
      "title": "Bullseye",
      "blurb": "Two lumps, one cell, one place it can go.",
      "map": "................\n................\n................\n................\n................\n..o.............\n.o.o....ooo.....\n..o.............\n................\n................\n................\n................",
      "par": 1,
      "solutions": 1,
      "gens": 49,
      "solution": [
        [
          2,
          6
        ]
      ]
    },
    {
      "key": "hairline",
      "title": "Hairline",
      "blurb": "Eight cells of dirt and exactly one answer.",
      "map": "................\n....oo..........\n....o.o.........\n.....o..........\n................\n................\n.ooo............\n................\n................\n................\n................\n................",
      "par": 1,
      "solutions": 1,
      "gens": 26,
      "solution": [
        [
          3,
          4
        ]
      ]
    },
    {
      "key": "split",
      "title": "Split",
      "blurb": "The wall separates them. One cell still does both.",
      "map": "................\n.........#......\n.........#......\n.........#......\n.....oo..#......\n.....o.o........\n......o.........\n................\n................\n........ooo.....\n................\n................",
      "par": 1,
      "solutions": 1,
      "gens": 15,
      "solution": [
        [
          8,
          7
        ]
      ]
    },
    {
      "key": "housekeeping",
      "title": "Housekeeping",
      "blurb": "Five lumps, eighteen cells of dirt, one cell of yours.",
      "map": "................\n.oo.............\n.oo........o....\n..........o.o...\n...........o....\n.....o..........\n.....o..........\n.oo..o..........\n.oo.......ooo...\n................\n................\n................",
      "par": 1,
      "solutions": 1,
      "gens": 71,
      "solution": [
        [
          7,
          7
        ]
      ]
    },
    {
      "key": "slow-burn",
      "title": "Slow burn",
      "blurb": "One cell, and well over a hundred generations of fallout.",
      "map": "................\n...ooo...oo.....\n.........oo#....\n...........#....\n...........#....\n...........#....\n................\n..........o.....\n.....oo...o.....\n.....oo...o.....\n................\n................",
      "par": 1,
      "solutions": 1,
      "gens": 137,
      "solution": [
        [
          9,
          8
        ]
      ]
    },
    {
      "key": "through-wall",
      "title": "Through the wall",
      "blurb": "Two cells. Only one pair in the whole board works.",
      "map": "................\n................\n.......o........\n.......o........\n.......o........\n.##########.....\n................\n.....o..........\n....o.o.........\n.....o..........\n................\n................",
      "par": 2,
      "solutions": 1,
      "gens": 64,
      "solution": [
        [
          6,
          6
        ],
        [
          6,
          7
        ]
      ]
    },
    {
      "key": "two-of-a-kind",
      "title": "Two of a kind",
      "blurb": "Symmetrical, and no kinder for it.",
      "map": "................\n........#.......\n.....o..#.o.....\n....o.o.#.o.....\n.....o..#.o.....\n........#.......\n........#.......\n........#.......\n................\n................\n................\n................",
      "par": 2,
      "solutions": 1,
      "gens": 84,
      "solution": [
        [
          5,
          3
        ],
        [
          9,
          3
        ]
      ]
    }
  ],
  "hold": [
    {
      "key": "hold-footing",
      "title": "Footing",
      "blurb": "Same idea as Clear, one extra rule: your own cells must outlast the dirt.",
      "map": "................\n........ooo.....\n................\n................\n...........ooo..\n................\n................\n................\n................\n................\n................\n................",
      "par": 2,
      "solutions": 9,
      "gens": 6,
      "solution": [
        [
          8,
          0
        ],
        [
          10,
          4
        ]
      ]
    },
    {
      "key": "hold-relay",
      "title": "Relay",
      "blurb": "Your lineage has to carry all the way to the end.",
      "map": "................\n................\n................\n.o..ooo.........\n.o..............\n.o..............\n................\n................\n................\n................\n................\n................",
      "par": 2,
      "solutions": 10,
      "gens": 10,
      "solution": [
        [
          1,
          2
        ],
        [
          6,
          2
        ]
      ]
    },
    {
      "key": "hold-bedrock",
      "title": "Bedrock again",
      "blurb": "You have cleared this board before. Now keep a cell of your own alive while you do it.",
      "map": "................\n................\n...ooo..........\n............o...\n.........o..o...\n....ooo..o..o...\n.........o......\n................\n................\n..##########....\n................\n................",
      "par": 2,
      "solutions": 9,
      "gens": 93,
      "solution": [
        [
          3,
          1
        ],
        [
          3,
          3
        ]
      ]
    },
    {
      "key": "hold-tenant",
      "title": "Tenant",
      "blurb": "Stay on the board.",
      "map": "................\n...ooo...oo.....\n........o..o....\n.........o.o....\n..........o.....\n................\n................\n................\n................\n................\n................\n................",
      "par": 2,
      "solutions": 8,
      "gens": 25,
      "solution": [
        [
          5,
          0
        ],
        [
          5,
          2
        ]
      ]
    },
    {
      "key": "hold-thread",
      "title": "By a thread",
      "blurb": "One pair of cells in the whole board manages it.",
      "map": "................\n................\n.o..............\n.o..............\n.o..............\n.....oo.........\n.....o.o........\n......o.........\n..........ooo...\n................\n................\n................",
      "par": 2,
      "solutions": 1,
      "gens": 18,
      "solution": [
        [
          9,
          6
        ],
        [
          9,
          8
        ]
      ]
    },
    {
      "key": "hold-wall",
      "title": "Last one out",
      "blurb": "Through the wall, and still standing at the end.",
      "map": "................\n................\n.......o........\n.......o........\n.......o........\n.##########.....\n................\n.....o..........\n....o.o.........\n.....o..........\n................\n................",
      "par": 2,
      "solutions": 1,
      "gens": 64,
      "solution": [
        [
          6,
          6
        ],
        [
          6,
          7
        ]
      ]
    }
  ],
  "bloom": [
    {
      "key": "bloom-sparks",
      "title": "Sparks",
      "blurb": "Two cells. Make as much life as you can by generation 40.",
      "map": "................\n....oo..........\n....o.o.........\n.....o..........\n................\n................\n.ooo............\n................\n................\n................\n................\n................",
      "gensLimit": 40,
      "budget": 2,
      "untouched": 8,
      "par": 55,
      "solution": [
        [
          5,
          2
        ],
        [
          2,
          5
        ]
      ]
    },
    {
      "key": "bloom-tinder",
      "title": "Tinder",
      "blurb": "The board barely changes on its own. Light it.",
      "map": "................\n................\n......ooo.......\n................\n.ooo............\n......ooo.......\n...........o....\n...........o....\n...........o....\n................\n................\n................",
      "gensLimit": 40,
      "budget": 2,
      "untouched": 10,
      "par": 64,
      "solution": [
        [
          13,
          5
        ],
        [
          7,
          6
        ]
      ]
    },
    {
      "key": "bloom-thicket",
      "title": "Thicket",
      "blurb": "Fourteen cells of dirt, sitting still.",
      "map": "................\n................\n..oo...oo.......\n.o..o..oo.......\n..o.o...........\n...o............\n................\n................\n................\n.......ooo......\n................\n................",
      "gensLimit": 40,
      "budget": 2,
      "untouched": 14,
      "par": 66,
      "solution": [
        [
          10,
          2
        ],
        [
          7,
          5
        ]
      ]
    },
    {
      "key": "bloom-orchard",
      "title": "Orchard",
      "blurb": "Nineteen already alive. Can you triple it?",
      "map": "................\n.o.........oo...\n.o.........o.o..\n.o..........o...\n................\n......o.........\n.oo...o....ooo..\n.o.o..o.........\n..o.............\n................\n................\n................",
      "gensLimit": 40,
      "budget": 2,
      "untouched": 19,
      "par": 70,
      "solution": [
        [
          12,
          4
        ],
        [
          4,
          5
        ]
      ]
    },
    {
      "key": "bloom-wildfire",
      "title": "Wildfire",
      "blurb": "The biggest swing on the board — from ten cells to sixty-odd.",
      "map": "................\n...........oo...\n..........o..o..\n...........o.o..\n.....ooo....o...\n................\n................\n................\n................\n................\n................\n................",
      "gensLimit": 40,
      "budget": 2,
      "untouched": 10,
      "par": 65,
      "solution": [
        [
          7,
          3
        ],
        [
          7,
          5
        ]
      ]
    }
  ],
  "sweep": [
    {
      "key": "sweep-band",
      "title": "Narrow band",
      "blurb": "Every marked cell has to be alive at least once. Fewer generations is better.",
      "map": "................\n................\n................\n....********....\n....********....\n....********....\n................\n................\n................\n................\n................\n................",
      "budget": 6,
      "targets": 24,
      "par": 13,
      "bestWhat": "rpent",
      "bestUsed": 5,
      "solution": [
        [
          9,
          4
        ],
        [
          10,
          4
        ],
        [
          8,
          5
        ],
        [
          9,
          5
        ],
        [
          9,
          6
        ]
      ]
    },
    {
      "key": "sweep-chamber",
      "title": "The chamber",
      "blurb": "A sealed room. Something in there has to touch every square.",
      "map": "................\n..############..\n..#**********#..\n..#**********#..\n..#**********#..\n..#**********#..\n..#**********#..\n..#**********#..\n..############..\n................\n................\n................",
      "budget": 8,
      "targets": 60,
      "par": 41,
      "bestWhat": "rpent",
      "bestUsed": 5,
      "solution": [
        [
          11,
          4
        ],
        [
          12,
          4
        ],
        [
          10,
          5
        ],
        [
          11,
          5
        ],
        [
          11,
          6
        ]
      ]
    },
    {
      "key": "sweep-diagonal",
      "title": "Diagonal run",
      "blurb": "A long slanted stripe, corner to corner.",
      "map": "****............\n.****...........\n..****..........\n...****.........\n....****........\n.....****.......\n......****......\n.......****.....\n........****....\n.........****...\n..........****..\n...........****.",
      "budget": 6,
      "targets": 48,
      "par": 48,
      "bestWhat": "rpent",
      "bestUsed": 5,
      "solution": [
        [
          13,
          5
        ],
        [
          14,
          5
        ],
        [
          12,
          6
        ],
        [
          13,
          6
        ],
        [
          13,
          7
        ]
      ]
    },
    {
      "key": "sweep-hall",
      "title": "The long hall",
      "blurb": "Wide open and too big to fill by hand. Something needs to travel.",
      "map": "................\n.##############.\n.*************..\n.*************..\n.*************..\n.*************..\n.*************..\n.##############.\n................\n................\n................\n................",
      "budget": 12,
      "targets": 65,
      "par": 23,
      "bestWhat": "lwss",
      "bestUsed": 9,
      "solution": [
        [
          12,
          2
        ],
        [
          15,
          2
        ],
        [
          11,
          3
        ],
        [
          11,
          4
        ],
        [
          15,
          4
        ],
        [
          11,
          5
        ],
        [
          12,
          5
        ],
        [
          13,
          5
        ],
        [
          14,
          5
        ]
      ]
    },
    {
      "key": "sweep-pillars",
      "title": "Pillars",
      "blurb": "Three bays behind stone. One seed cannot reach them all.",
      "map": "................\n................\n.***#***#***....\n.***#***#***....\n.***#***#***....\n.***#***#***....\n.***#***#***....\n................\n................\n................\n................\n................",
      "budget": 12,
      "targets": 45,
      "par": 40,
      "bestWhat": "rpent+diehard",
      "bestUsed": 12,
      "solution": [
        [
          1,
          8
        ],
        [
          1,
          9
        ],
        [
          2,
          7
        ],
        [
          2,
          8
        ],
        [
          3,
          8
        ],
        [
          12,
          4
        ],
        [
          6,
          3
        ],
        [
          7,
          3
        ],
        [
          7,
          2
        ],
        [
          11,
          2
        ],
        [
          12,
          2
        ],
        [
          13,
          2
        ]
      ]
    }
  ]
};
