/* Puzzle mode: clear every cell off a dirty board using as few new cells as
   possible. Unlike the other two modes these boards are bounded — a torus
   would make an escaping glider immortal, so the board could never empty.
   Levels and their pars come from levels.js, generated by the solver. */
(() => {
'use strict';

const LEVELS = window.LIFE_LEVELS;
const BUDGET = 400;              // generations before an attempt is given up on
const STORE = 'gol-puzzle-best';

/* -------------------------------------------------------------------- colors */
const PALETTE = {
  dead: '#0b0e13',
  rock: '#333c4f',
  mine: { fresh: '#eafff2', base: '#58d68d' },
  dirt: { fresh: '#f0dcc4', base: '#b0814e' },
};
const SETTLE = 12;

const hex = h => { const n = parseInt(h.slice(1), 16); return [n >> 16 & 255, n >> 8 & 255, n & 255]; };
const pack = ([r, g, b]) => (255 << 24 | b << 16 | g << 8 | r) >>> 0;
const mix = (a, b, t) => a.map((v, i) => Math.round(v + (b[i] - v) * t));
const DEAD_U32 = pack(hex(PALETTE.dead));
const ROCK_U32 = pack(hex(PALETTE.rock));
const LUT = (() => {
  const lut = new Uint32Array(512);
  [PALETTE.mine, PALETTE.dirt].forEach((side, s) => {
    const f = hex(side.fresh), b = hex(side.base);
    for (let i = 0; i < 256; i++) lut[s * 256 + i] = pack(mix(f, b, Math.min(i, SETTLE) / SETTLE));
  });
  return lut;
})();

/* ----------------------------------------------------------------------- dom */
const $ = id => document.getElementById(id);
const stage = $('stage'), canvas = $('view'), ctx = canvas.getContext('2d', { alpha: false });
const elHint = $('hint'), elRun = $('btn-run');

/* --------------------------------------------------------------------- state */
let level = null, levelIndex = 0;
let cols = 0, rows = 0, cellPx = 10, dpr = 1;
let own, nown, ages, rock, prev1, prev2;
let phase = 'edit';              // 'edit' | 'run' | 'done'
let used = 0, generation = 0, population = 0, revealed = false;
let dirty = true, showGrid = true, speed = 26;
const off = document.createElement('canvas');
const offCtx = off.getContext('2d', { alpha: false });
let imgData = null, buf32 = null;

const best = (() => { try { return JSON.parse(localStorage.getItem(STORE)) || {}; } catch { return {}; } })();
const saveBest = () => { try { localStorage.setItem(STORE, JSON.stringify(best)); } catch { /* private mode */ } };

/* --------------------------------------------------------------------- setup */
function loadLevel(i) {
  levelIndex = i;
  level = LEVELS[i];
  const lines = level.map.split('\n');
  rows = lines.length;
  cols = Math.max(...lines.map(l => l.length));
  const n = cols * rows;
  own = new Uint8Array(n); nown = new Uint8Array(n); ages = new Uint8Array(n);
  rock = new Uint8Array(n); prev1 = new Uint8Array(n); prev2 = new Uint8Array(n);
  for (let y = 0; y < rows; y++)
    for (let x = 0; x < lines[y].length; x++) {
      const c = lines[y][x], i2 = y * cols + x;
      if (c === 'o' || c === 'O') { own[i2] = 2; ages[i2] = 255; }
      else if (c === '#') rock[i2] = 1;
    }
  off.width = cols; off.height = rows;
  imgData = offCtx.createImageData(cols, rows);
  buf32 = new Uint32Array(imgData.data.buffer);

  phase = 'edit'; used = 0; generation = 0; revealed = false;
  countPopulation();
  $('result').classList.add('hidden');
  buildChips();
  layout();
  syncUI();
}

function resetLevel() { loadLevel(levelIndex); }

function layout() {
  const availW = Math.max(80, stage.clientWidth - 16), availH = Math.max(80, stage.clientHeight - 16);
  dpr = Math.min(window.devicePixelRatio || 1, 2);
  cellPx = Math.min(40, Math.max(4, Math.floor(Math.min(availW / cols, availH / rows))));
  canvas.style.width = cols * cellPx + 'px';
  canvas.style.height = rows * cellPx + 'px';
  canvas.width = Math.round(cols * cellPx * dpr);
  canvas.height = Math.round(rows * cellPx * dpr);
  ctx.imageSmoothingEnabled = false;
  dirty = true;
}

/* ---------------------------------------------------------------- simulation */
/* Bounded board: out of bounds counts as dead. Rock counts as dead too, and
   nothing is ever born on it. Colour follows the Immigration rule purely so
   you can watch your cells spread through the dirt. */
function step() {
  const w = cols, h = rows, o = own, no = nown;
  let pop = 0;
  for (let y = 0; y < h; y++) {
    const y0 = y > 0, y1 = y < h - 1;
    for (let x = 0; x < w; x++) {
      const i = y * w + x;
      if (rock[i]) { no[i] = 0; ages[i] = 0; continue; }
      const x0 = x > 0, x1 = x < w - 1;
      let n = 0, mine = 0;
      const tally = j => { const v = o[j]; if (v) { n++; if (v === 1) mine++; } };
      if (y0) { if (x0) tally(i - w - 1); tally(i - w); if (x1) tally(i - w + 1); }
      if (x0) tally(i - 1); if (x1) tally(i + 1);
      if (y1) { if (x0) tally(i + w - 1); tally(i + w); if (x1) tally(i + w + 1); }

      const self = o[i];
      let v = 0;
      if (self) { if (n === 2 || n === 3) v = self; }
      else if (n === 3) v = mine >= 2 ? 1 : 2;
      no[i] = v;
      ages[i] = v && v === self ? (ages[i] < 255 ? ages[i] + 1 : 255) : 0;
      if (v) pop++;
    }
  }
  const t = own; own = nown; nown = t;
  population = pop;
  generation++;
  dirty = true;
}

function countPopulation() {
  let p = 0;
  for (let i = 0, n = cols * rows; i < n; i++) if (own[i]) p++;
  population = p;
}

const settled = () => {
  const n = cols * rows;
  let s1 = true, s2 = true;
  for (let i = 0; i < n; i++) {
    if (own[i] !== prev1[i]) s1 = false;
    if (own[i] !== prev2[i]) s2 = false;
    if (!s1 && !s2) return false;
  }
  return true;
};

/* ------------------------------------------------------------------- drawing */
function render() {
  const n = cols * rows;
  for (let i = 0; i < n; i++) {
    const v = own[i];
    buf32[i] = v ? LUT[(v - 1) * 256 + ages[i]] : (rock[i] ? ROCK_U32 : DEAD_U32);
  }
  offCtx.putImageData(imgData, 0, 0);
  ctx.drawImage(off, 0, 0, cols, rows, 0, 0, canvas.width, canvas.height);
  const px = canvas.width / cols;
  if (showGrid && px / dpr >= 6) {
    ctx.strokeStyle = 'rgba(255,255,255,0.06)';
    ctx.lineWidth = 1;
    ctx.beginPath();
    for (let x = 1; x < cols; x++) { const gx = Math.round(x * px) + 0.5; ctx.moveTo(gx, 0); ctx.lineTo(gx, canvas.height); }
    const py = canvas.height / rows;
    for (let y = 1; y < rows; y++) { const gy = Math.round(y * py) + 0.5; ctx.moveTo(0, gy); ctx.lineTo(canvas.width, gy); }
    ctx.stroke();
  }
}

/* --------------------------------------------------------------------- input */
function cellAt(ev) {
  const r = canvas.getBoundingClientRect();
  const x = Math.floor((ev.clientX - r.left) / (r.width / cols));
  const y = Math.floor((ev.clientY - r.top) / (r.height / rows));
  return [x, y];
}

canvas.addEventListener('pointerdown', ev => {
  if (phase !== 'edit') return;
  ev.preventDefault();
  const [x, y] = cellAt(ev);
  if (x < 0 || y < 0 || x >= cols || y >= rows) return;
  const i = y * cols + x;
  if (rock[i]) { flash('Nothing can live on rock.'); return; }
  if (own[i] === 2) { flash('That is dirt — you cannot remove it by hand.'); return; }
  if (own[i] === 1) { own[i] = 0; used--; population--; }
  else { own[i] = 1; ages[i] = 0; used++; population++; }
  dirty = true;
  syncUI();
});
canvas.addEventListener('contextmenu', ev => ev.preventDefault());

/* ------------------------------------------------------------------- flow */
function startRun() {
  if (used === 0) { flash('Add at least one cell first.'); return; }
  phase = 'run';
  generation = 0;
  prev1.set(own); prev2.set(own);
  acc = 0; last = performance.now();
  syncUI();
}

function stopRun() { phase = 'edit'; syncUI(); }

function finish(won, reason) {
  phase = 'done';
  const key = level.key;
  if (won && !revealed && (best[key] === undefined || used < best[key])) { best[key] = used; saveBest(); }
  $('result-title').textContent = won
    ? (revealed ? 'Revealed' : used === level.par ? 'Par!' : 'Cleared')
    : 'Not clear';
  $('result-body').textContent = won
    ? (revealed
        ? `Cleared with the revealed solution in ${used} cell${used === 1 ? '' : 's'}, ${generation} generations. Reset and try it yourself to record a score.`
        : `${used} cell${used === 1 ? '' : 's'}, ${generation} generations. Par is ${level.par}.` +
          (used === level.par ? ' Nothing was wasted.' : ` ${used - level.par} more than needed.`))
    : reason;
  $('btn-next').disabled = levelIndex >= LEVELS.length - 1;
  $('result').classList.remove('hidden');
  buildChips();
  syncUI();
}

function reveal() {
  resetLevel();
  revealed = true;
  for (const [x, y] of level.solution) { const i = y * cols + x; if (!own[i]) { own[i] = 1; ages[i] = 0; used++; population++; } }
  dirty = true;
  flash(`A solution at par ${level.par}. Press Run to watch it.`);
  syncUI();
}

/* ------------------------------------------------------------------- chrome */
function buildChips() {
  const box = $('level-chips');
  box.innerHTML = '';
  LEVELS.forEach((l, i) => {
    const b = document.createElement('button');
    b.className = 'chip' + (i === levelIndex ? ' active' : '');
    const score = best[l.key];
    const mark = score === undefined ? '' : score === l.par ? ' ★' : ' ✓';
    b.innerHTML = `${i + 1}${mark}`;
    b.title = l.title;
    b.onclick = () => loadLevel(i);
    box.appendChild(b);
  });
}

let flashTimer = 0;
function flash(msg) {
  elHint.textContent = msg;
  clearTimeout(flashTimer);
  flashTimer = setTimeout(restoreHint, 2800);
}
function restoreHint() {
  if (phase === 'run') elHint.textContent = 'Running — every cell has to go, including yours.';
  else if (phase === 'done') elHint.textContent = 'Reset to try again, or pick another level.';
  else elHint.textContent = `Tap empty cells to add your own, then press Run. Par for this level is ${level.par} cell${level.par === 1 ? '' : 's'}.`;
}

function syncUI() {
  $('stat-used').textContent = used;
  $('stat-par').textContent = level.par;
  $('stat-gen').textContent = generation;
  $('stat-dirt').textContent = population;
  $('level-title').textContent = level.title;
  $('level-blurb').textContent = level.blurb;
  elRun.textContent = phase === 'run' ? '⏸ Stop' : '▶ Run';
  elRun.disabled = phase === 'done';
  $('btn-reveal').disabled = phase === 'run';
  $('stat-used').parentElement.classList.toggle('over', used > level.par);
  restoreHint();
}

elRun.onclick = () => (phase === 'run' ? stopRun() : startRun());
$('btn-reset').onclick = resetLevel;
$('btn-reveal').onclick = reveal;
$('btn-retry').onclick = resetLevel;
$('btn-next').onclick = () => loadLevel(Math.min(LEVELS.length - 1, levelIndex + 1));
$('btn-help').onclick = () => $('help').classList.remove('hidden');
$('btn-help-close').onclick = () => $('help').classList.add('hidden');
$('help').addEventListener('click', ev => { if (ev.target.id === 'help') $('help').classList.add('hidden'); });

const elSpeed = $('speed'), elSpeedOut = $('speed-out');
elSpeed.oninput = () => { speed = +elSpeed.value; elSpeedOut.textContent = speed + '/s'; };
$('gridlines').onchange = e => { showGrid = e.target.checked; dirty = true; };

window.addEventListener('keydown', ev => {
  if (ev.target.tagName === 'INPUT') return;
  const k = ev.key.toLowerCase();
  if (k === ' ' || k === 'enter') { ev.preventDefault(); if (phase !== 'done') elRun.click(); }
  else if (k === 'r') resetLevel();
  else if (k === 'escape') { $('help').classList.add('hidden'); $('result').classList.add('hidden'); }
  else if (k === 'n' && phase === 'done') $('btn-next').click();
});

/* ---------------------------------------------------------------------- loop */
let acc = 0, last = performance.now();
function frame(now) {
  const dt = Math.min(now - last, 250);
  last = now;
  if (phase === 'run') {
    acc += dt;
    const interval = 1000 / speed;
    let budget = 6;
    while (acc >= interval && phase === 'run' && budget-- > 0) {
      prev2.set(prev1); prev1.set(own);
      step();
      acc -= interval;
      if (population === 0) { finish(true); break; }
      if (settled()) { finish(false, `The board settled after ${generation} generations and will never die on its own. Reset and try a different placement.`); break; }
      if (generation >= BUDGET) { finish(false, `Still going after ${BUDGET} generations. Reset and try a different placement.`); break; }
    }
    if (acc > interval * 6) acc = 0;
    syncUI();
  }
  if (dirty) { render(); dirty = false; }
  requestAnimationFrame(frame);
}

/* --------------------------------------------------------------------- start */
let resizeTimer = 0;
const onResize = () => { clearTimeout(resizeTimer); resizeTimer = setTimeout(layout, 80); };
if (window.ResizeObserver) new ResizeObserver(onResize).observe(stage);
window.addEventListener('resize', onResize);
window.addEventListener('orientationchange', onResize);

elSpeedOut.textContent = speed + '/s';
loadLevel(0);
requestAnimationFrame(frame);
})();
