/* Builds ../levels.js. Every level is re-solved here, so the par that ships is
   a proven exhaustive minimum and the stored solution is checked to clear. */
'use strict';
const fs = require('fs');
const { parse, solve, run } = require('./solve');
const { mapFor } = require('./generate');
const BUDGET = 400;

const FIRST = `
................
................
................
................
................
.......oo.......
.......oo.......
................
................
................
................
................`;

const ORDER = [
  { map: FIRST, key: 'first-speck', title: 'First speck',  blurb: 'One block of grime. A single cell is enough — find where.' },
  { seed: 325,  key: 'loose-change', title: 'Loose change', blurb: 'Three lumps, and still only one cell needed.' },
  { seed: 258,  key: 'bedrock',      title: 'Bedrock',      blurb: 'Rock is inert: nothing lives there and you cannot build on it.' },
  { seed: 404,  key: 'odd-pair',     title: 'Odd pair',     blurb: 'This one wants two.' },
  { seed: 642,  key: 'quarry',       title: 'Quarry',       blurb: 'Plenty of dirt, plenty of rock, two cells.' },
  { seed: 411,  key: 'long-wall',    title: 'Long wall',    blurb: 'Five lumps split by a wall.' },
  { seed: 4,    key: 'bullseye',     title: 'Bullseye',     blurb: 'Two lumps, one cell, one place it can go.' },
  { seed: 64,   key: 'hairline',     title: 'Hairline',     blurb: 'Eight cells of dirt and exactly one answer.' },
  { seed: 60,   key: 'split',        title: 'Split',        blurb: 'The wall separates them. One cell still does both.' },
  { seed: 95,   key: 'housekeeping', title: 'Housekeeping', blurb: 'Five lumps, eighteen cells of dirt, one cell of yours.' },
  { seed: 66,   key: 'slow-burn',    title: 'Slow burn',    blurb: 'One cell, and well over a hundred generations of fallout.' },
  { seed: 300,  key: 'through-wall', title: 'Through the wall', blurb: 'Two cells. Only one pair in the whole board works.' },
  { seed: 192,  key: 'two-of-a-kind', title: 'Two of a kind', blurb: 'Symmetrical, and no kinder for it.' },
];

const out = [];
for (const spec of ORDER) {
  const map = (spec.map || mapFor(spec.seed)).replace(/^\n/, '').replace(/\n$/, '');
  const lvl = parse(map);

  if (run(lvl.dirt, lvl.w, lvl.h, lvl.rock, BUDGET)) throw new Error(`${spec.key}: clears itself`);
  let r = solve(lvl, { maxK: 2, dist: 4, cap: 400, budget: BUDGET });
  if (r.par === null) r = solve(lvl, { maxK: 3, dist: 3, cap: 100, budget: BUDGET });
  if (!r.par) throw new Error(`${spec.key}: no solution at k<=3`);

  const board = Uint8Array.from(lvl.dirt);
  for (const c of r.solutions[0]) board[c] = 1;
  const gens = run(board, lvl.w, lvl.h, lvl.rock, BUDGET);
  if (!gens) throw new Error(`${spec.key}: stored solution does not clear`);

  out.push({
    key: spec.key, title: spec.title, blurb: spec.blurb, map,
    par: r.par, solutions: r.solutions.length, gens,
    solution: r.solutions[0].map(i => [i % lvl.w, Math.floor(i / lvl.w)]),
  });
  console.log(`${String(out.length).padStart(2)}. ${spec.title.padEnd(17)} ${lvl.w}x${lvl.h}  par ${r.par}  ${String(r.solutions.length).padStart(3)} solution(s)  clears in ${String(gens).padStart(3)} gens`);
}

fs.writeFileSync(__dirname + '/../levels.js',
`/* Puzzle levels. Generated by tools/emit.js — do not edit by hand.

   Every par is a proven minimum: tools/solve.js searches all placements of k
   cells near the dirt, smallest k first, and simulates each to see whether the
   board empties. "solutions" is how many placements at par work, which is the
   honest measure of how tight a level is. The stored solution is one of them,
   used by the Reveal button.

   Map legend: '.' empty, 'o' dirt, '#' rock. */
window.LIFE_LEVELS = ${JSON.stringify(out, null, 2)};
`);
console.log(`\nwrote ../levels.js — ${out.length} levels, pars ${out.map(o => o.par).join('')}`);
